import { execSync } from "child_process";
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "fs";
import { join } from "path";

const projectRoot = join(__dirname, "..");
const outDir = join(projectRoot, "src", "wasm");

// 出力先ディレクトリの作成
if (!existsSync(outDir)) {
  mkdirSync(outDir, { recursive: true });
}
const buildDir = join(projectRoot, "build");
if (!existsSync(buildDir)) {
  mkdirSync(buildDir, { recursive: true });
}

console.log("Compiling AssemblyScript to WASM...");
try {
  // AssemblyScriptのコンパイル実行 (最適化レベル3、アサーション無効)
  execSync("bunx asc assembly/index.ts -o build/optimized.wasm -O3 --noAssert --enable simd", {
    cwd: projectRoot,
    stdio: "inherit",
  });
} catch (error) {
  console.error("Failed to compile WASM");
  process.exit(1);
}

// コンパイルされたWASMバイナリを読み込み、Base64文字列に変換
const wasmBuffer = readFileSync(join(projectRoot, "build", "optimized.wasm"));
const base64Wasm = wasmBuffer.toString("base64");

// 外部依存を無くすため、TypeScriptのファイル内に文字列としてWASMをインライン展開する
const tsContent = `// This file is auto-generated by scripts/build-wasm.ts
// Do not edit manually.

// コンパイル済みのWASMバイナリ (Base64エンコード済み)
export const wasmBase64 = "${base64Wasm}";
`;

writeFileSync(join(outDir, "wasm-binary.ts"), tsContent);
console.log("WASM binary embedded to src/wasm/wasm-binary.ts");
